import { useEffect, useState } from 'react'
import { Alert, Button, Card, Col, Form, Input, InputNumber, message, Modal, Row, Select, Space, Statistic, Table, Tabs, Tag } from 'antd'
import { ApartmentOutlined, BranchesOutlined, CloudSyncOutlined, DatabaseOutlined, DeploymentUnitOutlined, PlusOutlined, ReloadOutlined, SafetyCertificateOutlined } from '@ant-design/icons'
import api from '../api'
import PageHeader from '../components/PageHeader'

const rows = (payload:any) => payload?.results || payload || []
const pretty = (value:any) => JSON.stringify(value, null, 2)

export default function DataHubPage(){
  const [providers,setProviders]=useState<any[]>([]),[connections,setConnections]=useState<any[]>([]),[fields,setFields]=useState<any[]>([])
  const [mappings,setMappings]=useState<any[]>([]),[conflicts,setConflicts]=useState<any[]>([]),[raw,setRaw]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>({})
  const [connectionOpen,setConnectionOpen]=useState(false),[mappingOpen,setMappingOpen]=useState(false),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState('')
  const [connectionForm]=Form.useForm(),[mappingForm]=Form.useForm()
  const load=async()=>{try{const [p,c,f,m,d,r,a]=await Promise.all([
    api.get('/integration-providers/',{params:{page_size:100}}),api.get('/integration-connections/',{params:{page_size:100}}),api.get('/field-definitions/',{params:{page_size:200}}),
    api.get('/mapping-sets/',{params:{page_size:100}}),api.get('/data-conflicts/',{params:{page_size:100}}),api.get('/raw-records/',{params:{page_size:100}}).catch(()=>({data:[]})),api.get('/analytics/overview/')])
    setProviders(rows(p.data));setConnections(rows(c.data));setFields(rows(f.data));setMappings(rows(m.data));setConflicts(rows(d.data));setRaw(rows(r.data));setAnalytics(a.data)
  }catch(e:any){message.error(e.userMessage)}}
  useEffect(()=>{load()},[])
  const createConnection=async()=>{try{const v=await connectionForm.validateFields();await api.post('/integration-connections/',{...v,credentials:v.credentials?JSON.parse(v.credentials):{},settings:{use_mock:v.environment==='sandbox'}});message.success('连接实例已创建');setConnectionOpen(false);connectionForm.resetFields();load()}catch(e:any){message.error(e instanceof SyntaxError?'凭证必须是有效 JSON':e.userMessage||'创建失败')}}
  const operate=async(id:string,action:string)=>{setBusy(id+action);try{await api.post(`/integration-connections/${id}/${action}/`,action==='ingest'?{resource_type:'orders'}:{});message.success(action==='test_connection'?'连接测试完成':'同步完成');load()}catch(e:any){message.error(e.userMessage)}finally{setBusy('')}}
  const createMapping=async()=>{try{const v=await mappingForm.validateFields();const set=await api.post('/mapping-sets/',{name:v.name,connection:v.connection||null,resource_type:v.resource_type,description:v.description||''});const version=await api.post(`/mapping-sets/${set.data.id}/versions/`,{rules:JSON.parse(v.rules),sample:JSON.parse(v.sample)});const result=await api.post(`/mapping-sets/${set.data.id}/preview/`,{version_id:version.data.id,samples:[JSON.parse(v.sample)]});setPreview({...result.data,mapping_set_id:set.data.id,version_id:version.data.id});message.success('映射已校验，可检查结果后发布');load()}catch(e:any){message.error(e instanceof SyntaxError?'样本与规则必须是有效 JSON':e.userMessage||'映射失败')}}
  const publish=async()=>{if(!preview)return;try{await api.post(`/mapping-sets/${preview.mapping_set_id}/publish/`,{version_id:preview.version_id});message.success('不可变映射版本已发布');setMappingOpen(false);setPreview(null);mappingForm.resetFields();load()}catch(e:any){message.error(e.userMessage)}}
  const resolve=async(id:string,choice:string)=>{try{await api.post(`/data-conflicts/${id}/resolve/`,{choice});message.success('冲突处理结果已留痕');load()}catch(e:any){message.error(e.userMessage)}}
  const connectionColumns:any[]=[{title:'来源',dataIndex:'provider_name',render:(v:string,r:any)=><><b>{v}</b><br/><Tag>{r.source_kind}</Tag></>},{title:'连接实例',dataIndex:'name'},{title:'环境 / 区域',render:(_:any,r:any)=><span>{r.environment} · {r.region}</span>},{title:'能力',dataIndex:'enabled_capabilities',render:(v:string[])=><Space wrap>{(v||[]).slice(0,4).map(x=><Tag key={x}>{x}</Tag>)}</Space>},{title:'状态',dataIndex:'is_enabled',render:(v:boolean)=><Tag color={v?'green':'default'}>{v?'启用':'停用'}</Tag>},{title:'操作',render:(_:any,r:any)=><Space><Button size="small" loading={busy===r.id+'test_connection'} onClick={()=>operate(r.id,'test_connection')}>测试</Button><Button size="small" type="primary" loading={busy===r.id+'ingest'} onClick={()=>operate(r.id,'ingest')}>拉取变更</Button></Space>}]
  return <><PageHeader title="标准数据中台" subtitle="让每个渠道、ERP、WMS 与文件共享同一套 NEXUS 业务语言" actions={<Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setConnectionOpen(true)}>新建连接</Button></Space>}/>
    <section className="hub-hero"><div><Tag className="glow-tag">NEXUS CANONICAL DATA FABRIC</Tag><h2>接入一次，统一治理，全链路可解释。</h2><p>外部事实永久留在 Raw Layer，经版本化映射进入 Canonical Layer，再由 Semantic Layer 输出稳定指标。任何标准实体都能追溯来源、映射与修改事件。</p></div><div className="hub-layers"><div><DatabaseOutlined/><b>RAW</b><span>不可变原始事实</span></div><i>→</i><div><DeploymentUnitOutlined/><b>CANONICAL</b><span>NEXUS 标准实体</span></div><i>→</i><div><BranchesOutlined/><b>SEMANTIC</b><span>统一指标与分析</span></div></div></section>
    <Row gutter={14} className="hub-stats"><Col span={6}><Card><Statistic title="连接实例" value={connections.length} prefix={<CloudSyncOutlined/>}/></Card></Col><Col span={6}><Card><Statistic title="标准字段" value={fields.length} prefix={<ApartmentOutlined/>}/></Card></Col><Col span={6}><Card><Statistic title="原始事件" value={raw.length} prefix={<DatabaseOutlined/>}/></Card></Col><Col span={6}><Card><Statistic title="待处理冲突" value={conflicts.filter(x=>x.status==='open').length} prefix={<SafetyCertificateOutlined/>}/></Card></Col></Row>
    <Card className="hub-workbench"><Tabs items={[
      {key:'connections',label:'连接注册表',children:<Table rowKey="id" columns={connectionColumns} dataSource={connections} pagination={false}/>},
      {key:'fields',label:'字段目录',children:<Table rowKey="id" size="small" dataSource={fields} pagination={{pageSize:12}} columns={[{title:'标准字段',dataIndex:'key',render:(v:string)=><code>{v}</code>},{title:'中文名',dataIndex:'name_zh'},{title:'业务域',dataIndex:'domain',render:(v:string)=><Tag color="purple">{v}</Tag>},{title:'类型',dataIndex:'data_type'},{title:'权威来源',dataIndex:'authority'},{title:'分类',dataIndex:'classification'}]}/>},
      {key:'mapping',label:'映射中心',children:<><div className="tab-tools"><Alert showIcon type="info" message="映射发布后不可修改；变更会生成新版本，RawRecord 可随时重放。"/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setMappingOpen(true)}>创建映射</Button></div><Table rowKey="id" dataSource={mappings} pagination={false} columns={[{title:'名称',dataIndex:'name'},{title:'资源',dataIndex:'resource_type'},{title:'连接',dataIndex:'connection_name',render:(v:string)=>v||'通用文件映射'},{title:'当前版本',dataIndex:'current_version',render:(v:number)=>`v${v||0}`},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={v==='active'?'green':'gold'}>{v}</Tag>}]}/></>},
      {key:'conflicts',label:<span>冲突队列 <Tag color="red">{conflicts.filter(x=>x.status==='open').length}</Tag></span>,children:<Table rowKey="id" dataSource={conflicts} pagination={false} columns={[{title:'对象',dataIndex:'object_type'},{title:'字段',dataIndex:'field_key'},{title:'原因',dataIndex:'reason'},{title:'来源',render:(_:any,r:any)=>`${r.current_source} ↔ ${r.incoming_source}`},{title:'状态',dataIndex:'status'},{title:'处理',render:(_:any,r:any)=>r.status==='open'?<Space><Button size="small" onClick={()=>resolve(r.id,'keep_current')}>保留当前</Button><Button size="small" onClick={()=>resolve(r.id,'accept_incoming')}>接受来源</Button><Button size="small" onClick={()=>resolve(r.id,'ignore')}>忽略</Button></Space>:'已留痕'}]}/>},
      {key:'raw',label:'原始数据',children:<Table rowKey="id" size="small" dataSource={raw} pagination={{pageSize:10}} columns={[{title:'时间',dataIndex:'created_at',render:(v:string)=>new Date(v).toLocaleString()},{title:'来源',dataIndex:'provider'},{title:'对象',dataIndex:'object_type'},{title:'外部 ID',dataIndex:'external_id'},{title:'版本',dataIndex:'external_version'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag>{v}</Tag>},{title:'标准实体',render:(_:any,r:any)=>r.canonical_entity_id?<code>{String(r.canonical_entity_id).slice(0,8)}</code>:'—'}]}/>},
      {key:'analytics',label:'统一分析',children:<div className="semantic-grid"><div><span>统计窗口</span><b>{analytics.period_days||30} 天</b></div><div><span>GMV</span><b>¥{Number(analytics.gmv_original||0).toLocaleString()}</b></div><div><span>贡献利润</span><b>¥{Number(analytics.contribution_profit_cny||0).toLocaleString()}</b></div><div><span>可用库存</span><b>{Number(analytics.inventory?.on_hand||0)-Number(analytics.inventory?.reserved||0)}</b></div><pre>{pretty({channels:analytics.channels,top_skus:analytics.top_skus,metric_version:analytics.metric_version})}</pre></div>},
    ]}/></Card>
    <Modal title="新建集成连接" open={connectionOpen} onCancel={()=>setConnectionOpen(false)} onOk={createConnection} width={680}><Form form={connectionForm} layout="vertical" className="form-grid" initialValues={{environment:'sandbox',region:'NA',is_enabled:true,sync_interval_minutes:15,backfill_months:24}}><Form.Item name="provider" label="平台 / 系统" rules={[{required:true}]}><Select options={providers.filter(x=>x.key!=='file').map(x=>({value:x.id,label:`${x.name} · ${x.source_kind_label}`}))}/></Form.Item><Form.Item name="name" label="连接名称" rules={[{required:true}]}><Input placeholder="例如 Amazon US 主店"/></Form.Item><Form.Item name="environment" label="环境"><Select options={[{value:'sandbox',label:'沙箱 / 模拟'},{value:'production',label:'生产'}]}/></Form.Item><Form.Item name="region" label="区域"><Input/></Form.Item><Form.Item name="sync_interval_minutes" label="同步间隔（分钟）"><InputNumber min={5} style={{width:'100%'}}/></Form.Item><Form.Item name="backfill_months" label="历史回补（月）"><InputNumber min={1} max={24} style={{width:'100%'}}/></Form.Item><Form.Item className="full-span" name="credentials" label="凭证 JSON（加密存储，模拟环境可留空）"><Input.TextArea rows={5} placeholder='{"client_id":"...","client_secret":"..."}'/></Form.Item></Form></Modal>
    <Modal title="创建版本化字段映射" open={mappingOpen} onCancel={()=>{setMappingOpen(false);setPreview(null)}} onOk={preview?publish:createMapping} okText={preview?'发布此版本':'校验映射'} width={820}><Form form={mappingForm} layout="vertical" initialValues={{resource_type:'orders',sample:pretty({order_id:'EBAY-1001',created_at:'2026-09-10T08:00:00Z',total:'199.00',currency:'USD'}),rules:pretty([{source:'order_id',target:'order.channel_order_id',type:'string'},{source:'created_at',target:'order.ordered_at',type:'datetime'},{source:'total',target:'order.total',type:'money',currency:'USD'}])}}><Row gutter={14}><Col span={12}><Form.Item name="name" label="映射名称" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={6}><Form.Item name="connection" label="连接实例"><Select allowClear options={connections.map(x=>({value:x.id,label:x.name}))}/></Form.Item></Col><Col span={6}><Form.Item name="resource_type" label="资源"><Select options={['orders','inventory','catalog','finance'].map(x=>({value:x,label:x}))}/></Form.Item></Col></Row><Form.Item name="sample" label="源样本 JSON" rules={[{required:true}]}><Input.TextArea rows={7}/></Form.Item><Form.Item name="rules" label="安全映射规则 JSON" rules={[{required:true}]}><Input.TextArea rows={9}/></Form.Item>{preview&&<Alert type={preview.error_count?'error':'success'} showIcon message={`预览完成：${preview.success_count} 成功 / ${preview.error_count} 错误`} description={<pre className="mapping-preview">{pretty(preview.error_count?preview.errors:preview.output_sample)}</pre>}/>}</Form></Modal>
  </>
}
