import { useEffect, useState } from 'react'
import { Statistic, Tabs, Tag, type TableColumnsType } from 'antd'
import api from '../api'
import PageHeader from '../components/PageHeader'
import ResourceTable from '../components/ResourceTable'

export default function FinancePage(){
  const[report,setReport]=useState<any>({rows:[]});useEffect(()=>{api.get('/reports/profit/').then(r=>setReport(r.data))},[])
  const income=report.rows.find((x:any)=>x.entry_type==='revenue')?.amount||0;const costs=report.rows.filter((x:any)=>x.entry_type!=='revenue').reduce((n:number,x:any)=>n+Number(x.amount),0)
  const entryCols:TableColumnsType<any>=[{title:'发生时间',dataIndex:'occurred_at',render:v=>new Date(v).toLocaleString()},{title:'费用类型',dataIndex:'entry_type',render:v=><Tag>{v}</Tag>},{title:'订单',dataIndex:'order',render:v=>v||'—'},{title:'原币金额',dataIndex:'amount',render:(v,r)=>`${r.currency} ${Number(v).toFixed(2)}`},{title:'汇率',dataIndex:'exchange_rate'},{title:'本位币金额',dataIndex:'base_amount',render:v=><b>¥{Number(v).toFixed(2)}</b>},{title:'备注',dataIndex:'note'}]
  return <><PageHeader title="经营财务" subtitle="订单收入、平台费用、履约成本和贡献利润统一归集"/><div className="metric-grid" style={{marginBottom:20}}><div className="metric-card"><div className="metric-label">累计收入</div><Statistic value={income} precision={2} prefix="¥"/></div><div className="metric-card"><div className="metric-label">累计经营成本</div><Statistic value={costs} precision={2} prefix="¥"/></div><div className="metric-card"><div className="metric-label">贡献利润</div><Statistic value={Number(income)-costs} precision={2} prefix="¥" valueStyle={{color:'#159783'}}/></div><div className="metric-card"><div className="metric-label">核算币种</div><div className="metric-value">{report.currency||'CNY'}</div><div className="metric-note">永久保留原币与原始汇率</div></div></div><Tabs items={[
    {key:'entries',label:'收支明细',children:<ResourceTable endpoint="/finance-entries/" columns={entryCols} createTitle="新增财务记录" createFields={[{name:'entry_type',label:'类型',type:'select',required:true,options:[{label:'销售收入',value:'revenue'},{label:'商品成本',value:'product_cost'},{label:'平台佣金',value:'commission'},{label:'仓储费',value:'storage'},{label:'尾程运费',value:'last_mile'},{label:'头程运费',value:'first_mile'},{label:'关税',value:'duty'},{label:'VAT/销售税',value:'vat'},{label:'优惠券',value:'coupon'},{label:'广告费',value:'advertising'},{label:'退款',value:'refund'},{label:'退货损失',value:'return_loss'},{label:'其他',value:'other'}]},{name:'occurred_at',label:'发生时间（ISO）',required:true},{name:'currency',label:'币种',initialValue:'CNY',required:true},{name:'amount',label:'金额',type:'number',required:true},{name:'exchange_rate',label:'汇率',type:'number',initialValue:1},{name:'note',label:'备注',type:'textarea'}]}/>},
    {key:'settlements',label:'平台结算',children:<ResourceTable endpoint="/settlements/" columns={[{title:'结算单号',dataIndex:'external_id'},{title:'平台账号',dataIndex:'account'},{title:'期间',render:(_:unknown,r:any)=>`${r.period_start} — ${r.period_end}`},{title:'销售额',dataIndex:'gross_amount'},{title:'费用',dataIndex:'fee_amount'},{title:'退款',dataIndex:'refund_amount'},{title:'净额',dataIndex:'net_amount',render:(v:unknown,r:any)=><b>{r.currency} {String(v)}</b>},{title:'状态',dataIndex:'status'}]}/>},
    {key:'rates',label:'汇率',children:<ResourceTable endpoint="/exchange-rates/" columns={[{title:'日期',dataIndex:'rate_date'},{title:'原币',dataIndex:'from_currency'},{title:'本位币',dataIndex:'to_currency'},{title:'汇率',dataIndex:'rate'},{title:'来源',dataIndex:'source'}]} createTitle="维护汇率" createFields={[{name:'rate_date',label:'日期（YYYY-MM-DD）',required:true},{name:'from_currency',label:'原币',required:true},{name:'to_currency',label:'本位币',initialValue:'CNY',required:true},{name:'rate',label:'汇率',type:'number',required:true},{name:'source',label:'来源',initialValue:'manual'}]}/>} ]}/></>
}
