import { useState } from 'react'
import { Button, Form, message, Select, Space, Steps, Table, Upload, type UploadFile } from 'antd'
import { CloudUploadOutlined, DownloadOutlined, PlayCircleOutlined } from '@ant-design/icons'
import api from '../api'
import PageHeader from '../components/PageHeader'
import ResourceTable from '../components/ResourceTable'
import StatusPill from '../components/StatusPill'

const resources=[{label:'供应商',value:'suppliers'},{label:'商品与 SKU',value:'skus'},{label:'渠道 SKU 映射',value:'channel_mappings'},{label:'期初库存',value:'opening_inventory'}]

export default function ImportsPage(){
  const[form]=Form.useForm();const[fileList,setFileList]=useState<UploadFile[]>([]);const[job,setJob]=useState<any>(null);const[preview,setPreview]=useState<any>(null);const[step,setStep]=useState(0);const[busy,setBusy]=useState(false);const[refresh,setRefresh]=useState(0)
  const download=async()=>{try{const type=form.getFieldValue('resource_type')||'skus';const{data}=await api.get(`/import-templates/download/${type}/`,{responseType:'blob'});const url=URL.createObjectURL(data);const link=document.createElement('a');link.href=url;link.download=`${type}.xlsx`;link.click();URL.revokeObjectURL(url)}catch(e:any){message.error(e.userMessage)}}
  const upload=async()=>{try{const v=await form.validateFields();if(!fileList[0]?.originFileObj)return message.warning('请选择 Excel 文件');setBusy(true);const body=new FormData();body.append('resource_type',v.resource_type);body.append('file',fileList[0].originFileObj as Blob);body.append('mapping','{}');const{data}=await api.post('/imports/',body);setJob(data);const p=await api.post(`/imports/${data.id}/preview/`);setPreview(p.data);setStep(1);message.success('文件解析完成')}catch(e:any){if(e.userMessage)message.error(e.userMessage)}finally{setBusy(false)}}
  const execute=async()=>{setBusy(true);try{const{data}=await api.post(`/imports/${job.id}/execute/`);setJob(data);setStep(2);setRefresh(x=>x+1);message.success(`导入完成：成功 ${data.success_rows}，失败 ${data.error_rows}`)}catch(e:any){message.error(e.userMessage)}finally{setBusy(false)}}
  const columns=(preview?.rows?.[0]?Object.keys(preview.rows[0]):[]).map(key=>({title:key,dataIndex:key,key,ellipsis:true}))
  return <><PageHeader title="数据导入" subtitle="标准模板、字段映射、预览校验和逐行错误反馈" actions={<Button icon={<DownloadOutlined/>} onClick={download}>下载当前模板</Button>}/><div className="section-card" style={{marginBottom:22}}><Steps current={step} items={[{title:'上传文件'},{title:'预览校验'},{title:'执行结果'}]} style={{marginBottom:28}}/>{step===0&&<Form form={form} layout="vertical" style={{maxWidth:680}} initialValues={{resource_type:'skus'}}><Form.Item name="resource_type" label="导入数据类型" rules={[{required:true}]}><Select options={resources}/></Form.Item><Form.Item label="Excel 文件"><Upload.Dragger accept=".xlsx" maxCount={1} fileList={fileList} beforeUpload={()=>false} onChange={({fileList})=>setFileList(fileList)}><p style={{fontSize:28,margin:8}}><CloudUploadOutlined/></p><p>拖入或选择 .xlsx 文件</p><p style={{color:'#89948f',fontSize:12}}>建议先下载标准模板；同一业务键会更新已有数据</p></Upload.Dragger></Form.Item><Button type="primary" loading={busy} onClick={upload}>解析并预览</Button></Form>}{step===1&&<><div style={{marginBottom:14,color:'#66736d'}}>已识别字段：{preview.headers.join('、')}。下表展示前 {preview.rows.length} 行。</div><Table columns={columns} dataSource={preview.rows.map((x:any,i:number)=>({...x,_key:i}))} rowKey="_key" scroll={{x:900}} pagination={false}/><Space style={{marginTop:18}}><Button onClick={()=>setStep(0)}>重新选择</Button><Button type="primary" icon={<PlayCircleOutlined/>} loading={busy} onClick={execute}>确认执行导入</Button></Space></>}{step===2&&<div style={{textAlign:'center',padding:28}}><h2>导入处理完成</h2><p>总行数 {job.total_rows} · 成功 {job.success_rows} · 错误 {job.error_rows}</p><Button onClick={()=>{setStep(0);setFileList([]);setJob(null);setPreview(null)}}>继续导入</Button></div>}</div><h3>导入历史</h3><ResourceTable endpoint="/imports/" refreshKey={refresh} columns={[{title:'创建时间',dataIndex:'created_at',render:v=>new Date(v).toLocaleString()},{title:'类型',dataIndex:'resource_type'},{title:'文件',dataIndex:'file',ellipsis:true},{title:'状态',dataIndex:'status',render:v=><StatusPill value={v}/>},{title:'总行数',dataIndex:'total_rows'},{title:'成功',dataIndex:'success_rows'},{title:'错误',dataIndex:'error_rows'}]}/></>
}
