import { useEffect, useState } from 'react'
import { Button, Form, Input, InputNumber, message, Modal, Select, Space, Tabs, Tag, type TableColumnsType } from 'antd'
import { CalculatorOutlined, EditOutlined } from '@ant-design/icons'
import api from '../api'
import PageHeader from '../components/PageHeader'
import ResourceTable from '../components/ResourceTable'
import StatusPill from '../components/StatusPill'

export default function InventoryPage(){
  const [refresh,setRefresh]=useState(0);const [adjustOpen,setAdjustOpen]=useState(false);const [form]=Form.useForm();const [warehouses,setWarehouses]=useState<any[]>([]);const[skus,setSkus]=useState<any[]>([])
  useEffect(()=>{Promise.all([api.get('/warehouses/',{params:{page_size:500}}),api.get('/skus/',{params:{page_size:500}})]).then(([w,s])=>{setWarehouses(w.data.results.map((x:any)=>({label:`${x.code} · ${x.name}`,value:x.id})));setSkus(s.data.results.map((x:any)=>({label:`${x.code} · ${x.name}`,value:x.id})))})},[])
  const adjust=async()=>{try{const values=await form.validateFields();await api.post('/inventory-balances/adjust/',values,{headers:{'X-Idempotency-Key':crypto.randomUUID()}});message.success('库存调整已记入流水');setAdjustOpen(false);form.resetFields();setRefresh(x=>x+1)}catch(e:any){if(e.userMessage)message.error(e.userMessage)}}
  const generate=async()=>{try{const r=await api.post('/replenishment-suggestions/generate/',{window_days:30});message.success(`已生成 ${r.data.length} 条建议`);setRefresh(x=>x+1)}catch(e:any){message.error(e.userMessage)}}
  const approve=async(id:string)=>{try{await api.post(`/replenishment-suggestions/${id}/approve/`,{});message.success('补货建议已审批');setRefresh(x=>x+1)}catch(e:any){message.error(e.userMessage)}}
  const balanceCols:TableColumnsType<any>=[{title:'SKU',dataIndex:'sku_code',fixed:'left',width:170},{title:'商品',dataIndex:'sku_name',width:220},{title:'仓库',dataIndex:'warehouse_name',width:170},{title:'现有量',dataIndex:'on_hand'},{title:'预占',dataIndex:'reserved'},{title:'可用量',dataIndex:'available',render:v=><b style={{color:Number(v)<=0?'#b13b2d':'#0b7a58'}}>{v}</b>},{title:'在途',dataIndex:'in_transit'},{title:'残次',dataIndex:'damaged'},{title:'平均成本',dataIndex:'average_cost'}]
  const replCols:TableColumnsType<any>=[{title:'SKU',dataIndex:'sku_code'},{title:'仓库',dataIndex:'warehouse_name'},{title:'日均销量',dataIndex:'daily_velocity'},{title:'建议数量',dataIndex:'suggested_quantity',render:v=><b>{v}</b>},{title:'预计缺货',dataIndex:'expected_stockout_at',render:v=>v||'暂无'},{title:'建议下单',dataIndex:'suggested_order_at'},{title:'状态',dataIndex:'status',render:v=><StatusPill value={v}/>},{title:'操作',render:(_,r)=>r.status==='open'?<Button type="link" onClick={()=>approve(r.id)}>审批</Button>:null}]
  return <><PageHeader title="仓储库存" subtitle="统一查看自有仓、海外仓、FBA/WFS 与在途库存" actions={<Space><Button icon={<CalculatorOutlined/>} onClick={generate}>生成补货建议</Button><Button type="primary" icon={<EditOutlined/>} onClick={()=>setAdjustOpen(true)}>库存调整</Button></Space>}/><Tabs items={[
    {key:'balance',label:'库存余额',children:<ResourceTable endpoint="/inventory-balances/" columns={balanceCols} refreshKey={refresh}/>},
    {key:'ledger',label:'库存流水',children:<ResourceTable endpoint="/inventory-ledger/" columns={[{title:'时间',dataIndex:'created_at',width:180,render:v=>new Date(v).toLocaleString()},{title:'仓库',dataIndex:'warehouse_name'},{title:'SKU',dataIndex:'sku_code'},{title:'类型',dataIndex:'movement_type',render:v=><Tag>{v}</Tag>},{title:'库存变化',dataIndex:'quantity_delta'},{title:'预占变化',dataIndex:'reserved_delta'},{title:'在途变化',dataIndex:'in_transit_delta'},{title:'残次变化',dataIndex:'damaged_delta'},{title:'关联单号',dataIndex:'reference_id'}]}/>},
    {key:'warehouses',label:'仓库与节点',children:<ResourceTable endpoint="/warehouses/" columns={[{title:'编码',dataIndex:'code'},{title:'仓库',dataIndex:'name'},{title:'类型',dataIndex:'type',render:v=><Tag>{v}</Tag>},{title:'国家',dataIndex:'country'},{title:'履约节点',dataIndex:'fulfillment_node',render:v=>v||'—'},{title:'优先级',dataIndex:'priority'},{title:'状态',dataIndex:'is_active',render:v=><StatusPill value={v?'active':'disabled'}/>}] }/>},
    {key:'replenishment',label:'智能补货',children:<ResourceTable endpoint="/replenishment-suggestions/" columns={replCols} refreshKey={refresh} extraTools={<Button icon={<CalculatorOutlined/>} onClick={generate}>重新计算</Button>}/>},
  ]}/><Modal title="库存调整" open={adjustOpen} onCancel={()=>setAdjustOpen(false)} onOk={adjust} okText="记入流水"><Form form={form} layout="vertical" style={{marginTop:20}}><Form.Item name="warehouse" label="仓库" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={warehouses}/></Form.Item><Form.Item name="sku" label="SKU" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={skus}/></Form.Item><Form.Item name="movement_type" label="调整类型" initialValue="count_adjust"><Select options={[{label:'盘点调整',value:'count_adjust'},{label:'期初库存',value:'opening'},{label:'残次/报废',value:'damage'},{label:'外部同步',value:'external_sync'}]}/></Form.Item><Form.Item name="quantity_delta" label="库存变化（减少填负数）" rules={[{required:true}]}><InputNumber style={{width:'100%'}}/></Form.Item><Form.Item name="unit_cost" label="单位成本" initialValue={0}><InputNumber style={{width:'100%'}}/></Form.Item><Form.Item name="note" label="调整原因" rules={[{required:true}]}><Input.TextArea/></Form.Item></Form></Modal></>
}
