# Generated by Django 6.0.8 on 2026-09-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='importtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='receiptitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='replenishmentsuggestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockcount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='syncjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transferitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='in_transit_delta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
