# Generated by Django 6.0.8 on 2026-09-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_allocation_options_alter_apikey_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnorder',
            options={},
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('company', 'external_id'), name='uniq_finance_external'),
        ),
        migrations.AddConstraint(
            model_name='returnorder',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('company', 'external_id'), name='uniq_return_external'),
        ),
    ]
